version: 2
# Workaround for https://github.com/dependabot/dependabot-core/issues/6888
registries:
  maven-google:
    type: maven-repository
    url: "https://dl.google.com/dl/android/maven2/"
  maven-gradle-plugin-portal:
    type: maven-repository
    url: "https://plugins.gradle.org/m2"
  maven-jitpack:
    type: maven-repository
    url: "http://jitpack.io/"
  maven-central:
    type: maven-repository
    url: "https://repo1.maven.org/maven2/"

updates:
# Gradle updates
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
    timezone: Asia/Singapore
  open-pull-requests-limit: 10
  labels:
    - "dependabot: gradle"
    - "pr: dependency update"
# GitHub Actions updates
- package-ecosystem: github-actions
  directory: "/"
  registries:
    - maven-google
    - maven-gradle-plugin-portal
    - maven-central
    - maven-jitpack
  schedule:
    interval: weekly
    day: monday
    time: "07:00"
    timezone: Asia/Singapore
  open-pull-requests-limit: 5
  labels:
    - "dependabot: github-actions"
    - "pr: dependency update"
