version: 2
registries:
  # Workaround for https://github.com/dependabot/dependabot-core/issues/6888
  maven-google:
    type: maven-repository
    url: "https://dl.google.com/dl/android/maven2/"
updates:
# Gradle updates
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
    timezone: Asia/Singapore
  open-pull-requests-limit: 10
  labels:
    - "dependabot: gradle"
    - "pr: dependency update"
# GitHub Actions updates
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: monday
    time: "07:00"
    timezone: Asia/Singapore
  open-pull-requests-limit: 5
  labels:
    - "dependabot: github-actions"
    - "pr: dependency update"
