[versions]
android-gradle = "7.4.0-alpha08"
deep-link-dispatch = "6.1.0"
firebase = "30.2.0"
kotlin = "1.7.10"
kotlinx-coroutines = "1.6.4"
markwon = "4.6.2"
moshi = "1.13.0"

[libraries]
# AndroidX dependencies
androidx-appcompat = "androidx.appcompat:appcompat:1.4.2"
androidx-browser = "androidx.browser:browser:1.4.0"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.2.0-alpha03"
androidx-core-ktx = "androidx.core:core-ktx:1.8.0"
androidx-preference-ktx = "androidx.preference:preference-ktx:1.2.0"
androidx-recyclerview-core = "androidx.recyclerview:recyclerview:1.3.0-beta01"
androidx-recyclerview-selection = "androidx.recyclerview:recyclerview-selection:1.2.0-alpha01"
androidx-swiperefreshlayout = "androidx.swiperefreshlayout:swiperefreshlayout:1.2.0-alpha01"
androidx-work-runtime-ktx = "androidx.work:work-runtime-ktx:2.8.0-alpha02"

# Other dependencies

materialComponents = "com.google.android.material:material:1.7.0-alpha02"

# DeepLinkDispatcher
deepLinkDispatch-core = { module = "com.airbnb:deeplinkdispatch", version.ref = "deep-link-dispatch" }
deepLinkDispatch-processor = { module = "com.airbnb:deeplinkdispatch-processor", version.ref = "deep-link-dispatch" }

# Firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase" }
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx" }
playServices-auth = "com.google.android.gms:play-services-auth:20.2.0"
firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebase-dynamicLinks-ktx = { module = "com.google.firebase:firebase-dynamic-links-ktx" }
firebase-firestore-ktx = { module = "com.google.firebase:firebase-firestore-ktx" }
firebase-installations-ktx = { module = "com.google.firebase:firebase-installations-ktx" }
firebase-messaging-ktx = { module = "com.google.firebase:firebase-messaging-ktx" }
firebase-perf-ktx = { module = "com.google.firebase:firebase-perf-ktx" }

# Kotlin
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }

# Google Play Services OSS Licenses
playServices-ossLicenses-core = "com.google.android.gms:play-services-oss-licenses:17.0.0"
# (The following line is still needed as there is no plugin marker available as of yet)
playServices-ossLicenses-gradle = "com.google.android.gms:oss-licenses-plugin:0.10.5"

# Markwon
markwon-core = { module = "io.noties.markwon:core", version.ref = "markwon" }
markwon-editor = { module = "io.noties.markwon:editor", version.ref = "markwon" }
markwon-html = { module = "io.noties.markwon:html", version.ref = "markwon" }
markwon-imageCoil = { module = "io.noties.markwon:image-coil", version.ref = "markwon" }
markwon-linkify = { module = "io.noties.markwon:linkify", version.ref = "markwon" }
markwon-syntaxHighlight = { module = "io.noties.markwon:syntax-highlight", version.ref = "markwon" }
markwon-ext-strikethrough = { module = "io.noties.markwon:ext-strikethrough", version.ref = "markwon" }
markwon-ext-tables = { module = "io.noties.markwon:ext-tables", version.ref = "markwon" }
markwon-ext-tasklist = { module = "io.noties.markwon:ext-tasklist", version.ref = "markwon" }

# I/O Dependencies

# Coil
coil = "io.coil-kt:coil:2.1.0"

# Moshi
moshi-core = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-kotlinCodegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

# Miscellaneous

materialAbout = "com.github.daniel-stoneuk:material-about-library:3.2.0-rc01"
appUpdater = "com.github.javiersantos:AppUpdater:2.7"
imagePicker = "com.github.esafirm:android-image-picker:3.0.0-beta5"

# Gradle Versions (declared here as a library and not as a plugin
# such that it can be used in a custom reporter)
gradleVersions-gradle = "com.github.ben-manes:gradle-versions-plugin:0.42.0"

# Testing dependencies
androidx-test-espresso-core = "androidx.test.espresso:espresso-core:3.5.0-alpha07"
androidx-test-core = "androidx.test:core:1.5.0-alpha01"
androidx-test-ext = "androidx.test.ext:junit:1.1.4-alpha07"
androidx-test-runner = "androidx.test:runner:1.5.0-alpha04"
androidx-test-rules = "androidx.test:rules:1.4.1-alpha07"
junit = "junit:junit:4.13.2"
mockito-core = "org.mockito:mockito-core:4.6.1"

[bundles]
androidx-test = [
  "androidx-test-espresso-core", "androidx-test-core",
  "androidx-test-runner", "androidx-test-rules"
]
firebase = [
  "firebase-analytics-ktx", "firebase-auth-ktx", "playServices-auth",
  "firebase-crashlytics-ktx", "firebase-dynamicLinks-ktx", "firebase-firestore-ktx",
  "firebase-installations-ktx", "firebase-messaging-ktx", "firebase-perf-ktx"
]
markwon = [
  "markwon-core", "markwon-editor", "markwon-html",
  "markwon-imageCoil", "markwon-linkify", "markwon-syntaxHighlight",
  "markwon-ext-strikethrough", "markwon-ext-tables", "markwon-ext-tasklist"
]

[plugins]
android-gradle-application = { id = "com.android.application", version.ref = "android-gradle" }
android-gradle-library = { id = "com.android.library", version.ref = "android-gradle" }
buildProperties = "com.novoda.build-properties:0.4.1"
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
firebase-crashlytics = "com.google.firebase.crashlytics:2.9.1"
firebase-perf = "com.google.firebase.firebase-perf:1.4.1"
googleServices = "com.google.gms.google-services:4.3.13"
gradleVersions = "com.github.ben-manes.versions:0.42.0"
gradleVersions-catalog = "nl.littlerobots.version-catalog-update:0.3.1"
