syntax = "proto3";

package com.edricchan.studybuddy.core.settings.appearance.proto;

import "com/edricchan/studybuddy/core/settings/appearance/proto/settings_appearance_theme.proto";
import "com/edricchan/studybuddy/core/settings/appearance/proto/settings_appearance_dark_mode.proto";
import "com/edricchan/studybuddy/core/settings/appearance/proto/settings_appearance_typeface.proto";

option java_multiple_files = true;

message AppearanceSettings {
  /** The theme to use. */
  AppThemeSettingProto theme = 1;
  /* Whether to enable dark mode. */
  DarkModeSettingProto dark_mode = 2;
  /* The typeface to use for display styles (headers). */
  TypefaceSettingProto display_typeface = 3;
  /* The typeface to use for body text. */
  TypefaceSettingProto body_typeface = 4;
  /*
    The desired base spacing value to use.
    Note: Consumers should provide a more intuitive user interface (for example, a preset list of
    possible values) when setting this value from the user's end.
  */
  int32 base_spacing = 5;

  // Formerly the use_relative_timestamps setting which is now
  // located in TemporalFormattingSettings
  reserved 100;
}
