# Reusable workflow for running Gradle tasks

on:
  workflow_call:
    inputs:
      gradle-cache-read-only:
        description: "Whether to disallow writing Gradle cache."
        default: false
        required: false
        type: boolean
      gradle-arguments:
        description: "Arguments to be passed to ./gradlew for building."
        required: true
        type: string
      skip-upload:
        description: "Whether to skip uploading."
        required: false
        default: false
        type: boolean
      upload-name:
        description: "The name of the artifact to upload."
        required: true
        type: string
      upload-path:
        description: "The path to the artifact to upload."
        required: true
        type: string
    secrets:
      transcrypt-cipher:
        description: "The cipher to use for Transcrypt."
        required: true
      transcrypt-password:
        description: "The password to use for the encrypted Transcrypt files."
        required: true
      app-keystore-password:
        description: "The keystore password to use."
        required: true
      app-keystore-alias:
        description: "The alias to use for the keystore."
        required: true
      app-keystore-alias-password:
        description: "The keystore alias password to use."
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt
      - name: Install Homebrew dependencies
        run: brew bundle
      - name: Decrypt keystore
        run: |
          source ~/.profile
          echo "Current version of transcrypt:"
          transcrypt -v
          transcrypt -c ${{ secrets.transcrypt-cipher }} -p ${{ secrets.transcrypt-password }} -y
        env:
          SECRETS_GPG_COMMAND: gpg2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ inputs.gradle-cache-read-only }}
      - name: Setup Android problem matchers
        uses: jonasb/android-problem-matchers-action@v1
      - name: Build Android
        run: |
          source ~/.profile
          ./gradlew ${{ inputs.gradle-arguments }}
        env:
          APP_KEYSTORE_PASSWORD: ${{ secrets.app-keystore-password }}
          APP_KEYSTORE_ALIAS: ${{ secrets.app-keystore-alias }}
          APP_KEYSTORE_ALIAS_PASSWORD: ${{ secrets.app-keystore-alias-password }}
      - name: Upload artifacts
        if: ${{ !inputs.skip-upload }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.upload-name }}
          path: ${{ inputs.upload-path }}
